Remote Config added
m0skit0/hms-sdk-unity pull request #65
Opened 2020-11-30 05:26 UTC by kayahanbaskeser

Remote Config added

2020-11-30 09:23 UTC, m0skit0 commented
Please use C# naming conventions, methods start with uppercase, thanks.

2020-11-30 11:41 UTC, m0skit0 requested changes

2020-11-30 11:41 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/RemoteConfig/AGConnectConfigWrapper.cs
> +        public void setDeveloperMode(bool isDeveloperMode) => Call("setDeveloperMode", isDeveloperMode);
Property

2020-11-30 11:41 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/RemoteConfig/AGConnectConfigWrapper.cs
> +        public Constants.SOURCE getSource(string key) => Call<Constants.SOURCE>("getSource", key);
Are you sure this is going to work? Returned value from Call is a Java enum.

2020-11-30 11:41 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/RemoteConfig/DEFAULT.cs
> +        public static byte[] BYTE_ARRAY_VALUE = new byte[0];
Don't hardcode values, use the values returned by the SDK.

2020-11-30 11:41 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Utils/DictionaryOperations.cs
> +                    "(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;");
Why this? Just use Call("put") like you do on AndroidJavaObjectToDictionary

2020-11-30 11:41 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Utils/DictionaryOperations.cs
> +    public static class DictionaryOperations
Why public? This should be internal.

2020-11-30 11:41 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Utils/DictionaryOperations.cs
> +        public static AndroidJavaObject DictionaryToAndroidJavaObject(IDictionary<String, System.Object> dictionary)
Internal not public
Transform to extension method and follow naming in other utils, like ToJavaHashMap()

2020-11-30 11:41 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Utils/DictionaryOperations.cs
> +        public static Dictionary<String, System.Object> XMLtoDictionary(String xmlPath)
What is this used for?

2020-11-30 11:41 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Utils/DictionaryOperations.cs
> +        public static Dictionary<String, System.Object> AndroidJavaObjectToDictionary(AndroidJavaObject javaList)
Internal not public
Transform to extension method and follow naming in other utils, like ToDictionary().

2020-11-30 11:41 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Utils/DictionaryOperations.cs
> +            if (javaList == null || javaList.Call<int>("size") == 0) return null;
Return empty Dictionary instead of null

2020-11-30 12:57 UTC, kayahanbaskeser commented on hms-sdk-unity/HuaweiMobileServices/Utils/DictionaryOperations.cs
> +        public static Dictionary<String, System.Object> XMLtoDictionary(String xmlPath)
with this function, i read xml file and convert it to dictionary

2020-12-02 16:56 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Utils/DictionaryOperations.cs
> +        public static Dictionary<String, System.Object> XMLtoDictionary(String xmlPath)
Yes I understand, but why we need this? What XML are we reading?

2020-12-02 16:57 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Utils/DictionaryOperations.cs
> +        public static Dictionary<String, System.Object> AndroidJavaObjectToDictionary(AndroidJavaObject javaList)
Sorry, AsDictionary

2020-12-04 06:54 UTC, kayahanbaskeser commented
> Please use C# naming conventions, methods start with uppercase, thanks.

2020-12-04 06:57 UTC, kayahanbaskeser commented on hms-sdk-unity/HuaweiMobileServices/RemoteConfig/AGConnectConfigWrapper.cs
> +        public void setDeveloperMode(bool isDeveloperMode) => Call("setDeveloperMode", isDeveloperMode);
its done

2020-12-04 06:59 UTC, kayahanbaskeser commented on hms-sdk-unity/HuaweiMobileServices/RemoteConfig/AGConnectConfigWrapper.cs
> +        public Constants.SOURCE getSource(string key) => Call<Constants.SOURCE>("getSource", key);
you are right, this part did not work, I updated it

2020-12-04 06:59 UTC, kayahanbaskeser commented on hms-sdk-unity/HuaweiMobileServices/RemoteConfig/DEFAULT.cs
> +        public static byte[] BYTE_ARRAY_VALUE = new byte[0];
its done

2020-12-04 06:59 UTC, kayahanbaskeser commented on hms-sdk-unity/HuaweiMobileServices/Utils/DictionaryOperations.cs
> +    public static class DictionaryOperations
its done

2020-12-04 06:59 UTC, kayahanbaskeser commented on hms-sdk-unity/HuaweiMobileServices/Utils/DictionaryOperations.cs
> +        public static AndroidJavaObject DictionaryToAndroidJavaObject(IDictionary<String, System.Object> dictionary)
it`s done

2020-12-04 07:00 UTC, kayahanbaskeser commented on hms-sdk-unity/HuaweiMobileServices/Utils/DictionaryOperations.cs
> +        public static Dictionary<String, System.Object> XMLtoDictionary(String xmlPath)
in remoteconfig, there is a method applydefault. and this method gets value from xml.

2020-12-04 07:01 UTC, kayahanbaskeser commented on hms-sdk-unity/HuaweiMobileServices/Utils/DictionaryOperations.cs
> +        public static Dictionary<String, System.Object> AndroidJavaObjectToDictionary(AndroidJavaObject javaList)
it`s done

2020-12-04 07:01 UTC, kayahanbaskeser commented on hms-sdk-unity/HuaweiMobileServices/Utils/DictionaryOperations.cs
> +            if (javaList == null || javaList.Call<int>("size") == 0) return null;
it`s done

2020-12-04 07:02 UTC, kayahanbaskeser commented on hms-sdk-unity/HuaweiMobileServices/Utils/DictionaryOperations.cs
> +                    "(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;");
when i use call("put", "key", "value"), it gives error

2020-12-04 10:08 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Utils/DictionaryOperations.cs
> +                    "(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;");
Which error, please be specific.

2020-12-04 10:16 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/RemoteConfig/DEFAULT.cs
> +        public static byte[] BYTE_ARRAY_VALUE = new byte[0];
You moved DEFAULT inner class to AGConnectConfig?

2020-12-04 10:22 UTC, m0skit0 requested changes

2020-12-04 10:22 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Utils/DictionaryOperations.cs
> +        internal static Dictionary<string, object> XMLtoDictionary(String xmlPath)
I still don't understand why we have this method, can you please explain? Where we use this?

2020-12-04 10:28 UTC, kayahanbaskeser commented on hms-sdk-unity/HuaweiMobileServices/RemoteConfig/DEFAULT.cs
> +        public static byte[] BYTE_ARRAY_VALUE = new byte[0];
I realized that it was the place on sdk

2020-12-04 10:55 UTC, merged