saved games
m0skit0/hms-sdk-unity pull request #66
Opened 2020-11-30 06:47 UTC by gmYusuf

ranking scores function name issue fixed.
saved games functions added.

2020-11-30 09:44 UTC, m0skit0 requested changes

2020-11-30 09:44 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Utils/AndroidJavaLongClass.cs
> +﻿using System;
I don't understand what is the purpose of this class, can you please explain?

2020-11-30 09:44 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Utils/GenericBridgeCallbackWrapper.cs
> +    public class GenericBridgeCallbackWrapper : AndroidJavaProxy
Why public? This should not be accessed outside the SDK, you need to write an API to hide this.

2020-11-30 09:44 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Utils/GenericBridgeWrapper.cs
> +    public static class GenericBridgeWrapper
Why public? This should not be accessed outside the SDK, you need to write an API to hide this.

2020-11-30 09:56 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Utils/AndroidJavaLongClass.cs
> +﻿using System;
I have to create this because 
ArchiveSummaryUpdate and ArchiveSummaryUpdate.Builder class have a 'ActiveTime' and 'CurrentProgress' properties they are in document shows long but in builder their type is **L**ong. On c# when i want to use with long its give error sign miss match error because of that i create this class.

2020-11-30 09:58 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Utils/GenericBridgeCallbackWrapper.cs
> +    public class GenericBridgeCallbackWrapper : AndroidJavaProxy
![image](https://user-images.githubusercontent.com/8115505/100595178-a15fd080-330b-11eb-88da-89ca68045677.png)
For saved games i am using this bridge, you mean I should write one more class for hide this class?

2020-11-30 11:22 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Utils/AndroidJavaLongClass.cs
> +﻿using System;
Ok, then convert internally to C# long? and expose this value.

2020-11-30 11:27 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Utils/GenericBridgeCallbackWrapper.cs
> +    public class GenericBridgeCallbackWrapper : AndroidJavaProxy
See https://github.com/m0skit0/hms-sdk-unity/blob/master/hms-sdk-unity/HuaweiMobileServices/Base/Status.cs#L32

2020-11-30 11:36 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Utils/GenericBridgeCallbackWrapper.cs
> +    public class GenericBridgeCallbackWrapper : AndroidJavaProxy
I will update this.

2020-11-30 13:22 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Utils/GenericBridgeWrapper.cs
> +    public static class GenericBridgeWrapper
With new commit they are fixed

2020-12-01 10:20 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Game/ArchiveSummaryUpdate.cs
> +        AndroidJavaClass sJavaClass = new AndroidJavaClass(CLASS_NAME);
private

2020-12-01 10:20 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Game/ArchiveSummaryUpdate.cs
> +        public long ActiveTime
long? since it is a Java object Long and can be null

2020-12-01 10:20 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Game/ArchiveSummaryUpdate.cs
> +            get => AndroidJavaObjectExtensions.ToLong(sJavaClass.Call<AndroidJavaObject>("getActiveTime"));
Use as an extension method please, it's simpler to read

2020-12-01 10:20 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Game/ArchiveSummaryUpdate.cs
> +            get => AndroidJavaObjectExtensions.ToLong(sJavaClass.Call<AndroidJavaObject>("getCurrentProgress"));
Same comments as above

2020-12-01 10:20 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Game/ArchivesClientWrapper.cs
> +        public void ShowSavedGames(AndroidIntent androidIntent, Action onSuccess, Action<HMSException> onFailure)
Do we really need the Intent here? Can't we build the Intent ourselves instead of asking for it using getShowArchiveListIntent?

2020-12-01 10:20 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Game/IArchivesClient.cs
> +        void ShowSavedGames(AndroidIntent androidIntent, Action onSuccess, Action<HMSException> onFailure);
Is this not the same as void ShowArchiveListIntent(Action onSuccess, Action<HMSException> onFailure)?

2020-12-01 10:20 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Utils/AndroidJavaObjectExtensions.cs
> +        public static long  ToLong(this AndroidJavaObject javaLongObject)
AsLong better name, same as the other methods.
Should return `long?` not `long`

2020-12-01 10:20 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Utils/AndroidJavaObjectExtensions.cs
> +            return longValue;
If javaLongObject is null you will get an NPE exception here. Check if it is null and return null if so.
You don't need intermediate value, just return the call.
longValue() is not static in Java.

2020-12-01 10:20 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Utils/GenericBridgeWrapper.cs
> +        public static void ReceiveShow(AndroidJavaObject intent, GenericBridgeCallbackWrapper callback) => sJavaClass.CallStatic("receiveShow", intent, callback);
What is this for?

2020-12-01 11:26 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Utils/GenericBridgeWrapper.cs
> +        public static void ReceiveShow(AndroidJavaObject intent, GenericBridgeCallbackWrapper callback) => sJavaClass.CallStatic("receiveShow", intent, callback);
I will delete this.

2020-12-01 11:27 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Utils/AndroidJavaObjectExtensions.cs
> +            return longValue;
will be resolved

2020-12-01 11:27 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Utils/AndroidJavaObjectExtensions.cs
> +        public static long  ToLong(this AndroidJavaObject javaLongObject)
will be resolved

2020-12-01 11:27 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Game/ArchiveSummaryUpdate.cs
> +        AndroidJavaClass sJavaClass = new AndroidJavaClass(CLASS_NAME);
will be resolved

2020-12-01 11:27 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Game/ArchiveSummaryUpdate.cs
> +        public long ActiveTime
will be resolved

2020-12-01 11:27 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Game/ArchiveSummaryUpdate.cs
> +            get => AndroidJavaObjectExtensions.ToLong(sJavaClass.Call<AndroidJavaObject>("getActiveTime"));
will be resolved

2020-12-01 11:28 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Game/ArchiveSummaryUpdate.cs
> +            get => AndroidJavaObjectExtensions.ToLong(sJavaClass.Call<AndroidJavaObject>("getCurrentProgress"));
will be resolved

2020-12-01 11:35 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Game/ArchivesClientWrapper.cs
> +        public void ShowSavedGames(AndroidIntent androidIntent, Action onSuccess, Action<HMSException> onFailure)
We can do but in huawei document it show 2 ways because of that I added this one also.
https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/game-archive-0000001050121532#EN-US_TOPIC_0000001060505147__section196178301310

2020-12-01 11:36 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Game/IArchivesClient.cs
> +        void ShowSavedGames(AndroidIntent androidIntent, Action onSuccess, Action<HMSException> onFailure);
Its diffrent. It should need Intent as a parameter.

2020-12-01 15:29 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Game/ArchivesClientWrapper.cs
> +        public void ShowSavedGames(AndroidIntent androidIntent, Action onSuccess, Action<HMSException> onFailure)
Keep in mind most Unity dev does not understand what is an Android Intent, so not really useful. Please remove the AndroidIntent as parameter and recover internally. If someone asks for this feature we can add, no need for now.

2020-12-01 15:29 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Game/IArchivesClient.cs
> +        void ShowSavedGames(AndroidIntent androidIntent, Action onSuccess, Action<HMSException> onFailure);
Like we discussed above, it makes no sense to pass Intent here, so this is the same as the existing method ShowArchiveListIntent

2020-12-01 15:29 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Utils/AndroidJavaObjectExtensions.cs
> +                return javaLongObject.CallStatic<long>("longValue");
Not CallStatic, method is not static in Java.

2020-12-02 06:29 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Utils/AndroidJavaObjectExtensions.cs
> +                return javaLongObject.CallStatic<long>("longValue");
its done

2020-12-02 06:29 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Game/ArchivesClientWrapper.cs
> +        public void ShowSavedGames(AndroidIntent androidIntent, Action onSuccess, Action<HMSException> onFailure)
its done

2020-12-02 16:49 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Game/ArchivesClientWrapper.cs
> +            });
Please add OnError listener and log the error if any, otherwise very hard to debug if any error.

2020-12-02 16:49 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Utils/AndroidJavaObjectExtensions.cs
> +            else
No need for `else` :)

2020-12-02 16:54 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Game/ArchiveSummaryUpdate.cs
> +        AndroidJavaClass sJavaClass = new AndroidJavaClass(CLASS_NAME);
Don't forget this :)

2020-12-02 16:54 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Game/ArchiveSummaryUpdate.cs
> +        AndroidJavaClass sJavaClass = new AndroidJavaClass(CLASS_NAME);
Don't forget this :)

2020-12-02 20:33 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Game/ArchiveSummaryUpdate.cs
> +        AndroidJavaClass sJavaClass = new AndroidJavaClass(CLASS_NAME);
its done

2020-12-03 14:39 UTC, m0skit0 requested changes

2020-12-03 14:39 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Game/ArchiveSummaryUpdate.cs
> +        AndroidJavaClass sJavaClass = new AndroidJavaClass(CLASS_NAME);
I still see  `AndroidJavaClass sJavaClass = new AndroidJavaClass(CLASS_NAME);`, without `private static readonly`

2020-12-03 16:37 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Game/ArchiveSummaryUpdate.cs
> +        AndroidJavaClass sJavaClass = new AndroidJavaClass(CLASS_NAME);
![image](https://user-images.githubusercontent.com/8115505/101059110-f7987200-359e-11eb-8ccb-ed8046e56483.png)

Maybe it bug, I can see.

2020-12-04 10:05 UTC, m0skit0 requested changes

2020-12-04 10:05 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/HuaweiMobileServices.csproj
> +  </ItemGroup>
What is this? Please do not modify the csproj file without a valid reason.

2020-12-04 10:43 UTC, merged